"""create meeting model

Revision ID: 1c47eecc3c91
Revises: cf597eccf807
Create Date: 2025-09-06 10:40:25.136988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c47eecc3c91'
down_revision: Union[str, Sequence[str], None] = 'cf597eccf807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'canceled', name='meetingstatus'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_meeting_team_id_team'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting'))
    )
    op.create_index(op.f('ix_meeting_ends_at'), 'meeting', ['ends_at'], unique=False)
    op.create_index(op.f('ix_meeting_starts_at'), 'meeting', ['starts_at'], unique=False)
    op.create_index(op.f('ix_meeting_team_id'), 'meeting', ['team_id'], unique=False)
    op.create_index('ix_meeting_team_status', 'meeting', ['team_id', 'status'], unique=False)
    op.create_index('ix_meeting_time_window', 'meeting', ['starts_at', 'ends_at'], unique=False)
    op.create_table('meeting_participants',
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], name=op.f('fk_meeting_participants_meeting_id_meeting'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_meeting_participants_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meeting_id', 'user_id', name=op.f('pk_meeting_participants'))
    )
    op.create_index('ix_mp_user', 'meeting_participants', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mp_user', table_name='meeting_participants')
    op.drop_table('meeting_participants')
    op.drop_index('ix_meeting_time_window', table_name='meeting')
    op.drop_index('ix_meeting_team_status', table_name='meeting')
    op.drop_index(op.f('ix_meeting_team_id'), table_name='meeting')
    op.drop_index(op.f('ix_meeting_starts_at'), table_name='meeting')
    op.drop_index(op.f('ix_meeting_ends_at'), table_name='meeting')
    op.drop_table('meeting')
    # ### end Alembic commands ###
