"""Create Team mosel

Revision ID: 1fecc2f1ab40
Revises: e1d00bff856e
Create Date: 2025-08-23 11:42:35.470287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fecc2f1ab40'
down_revision: Union[str, Sequence[str], None] = 'e1d00bff856e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_team_owner_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team'))
    )
    op.add_column('user', sa.Column('team_fk', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_user_team_fk_team'), 'user', 'team', ['team_fk'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_team_fk_team'), 'user', type_='foreignkey')
    op.drop_column('user', 'team_fk')
    op.drop_table('team')
    # ### end Alembic commands ###
