"""add Task model

Revision ID: 0badceff3860
Revises: 46995a103fad
Create Date: 2025-08-28 12:48:06.634870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0badceff3860'
down_revision: Union[str, Sequence[str], None] = '46995a103fad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'done', name='status'), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['user.id'], name=op.f('fk_task_assignee_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk_task_author_id_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_task_team_id_team'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task'))
    )
    op.add_column('team', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('team', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'updated_at')
    op.drop_column('team', 'created_at')
    op.drop_table('task')
    # ### end Alembic commands ###
