"""add rated_at for Task model

Revision ID: d276c605cfc4
Revises: 5e862a081f29
Create Date: 2025-08-29 10:38:49.997109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd276c605cfc4'
down_revision: Union[str, Sequence[str], None] = '5e862a081f29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('rated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'rated_at')
    # ### end Alembic commands ###
