"""add rating for Task model

Revision ID: ca5a257cd822
Revises: 2b0785cdd51a
Create Date: 2025-08-29 06:00:40.678460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca5a257cd822'
down_revision: Union[str, Sequence[str], None] = '2b0785cdd51a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'rating')
    # ### end Alembic commands ###
