"""delete const

Revision ID: 16b1b7493e3c
Revises: a8cd8284c7d9
Create Date: 2025-10-20 14:35:26.623220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16b1b7493e3c'
down_revision: Union[str, Sequence[str], None] = 'a8cd8284c7d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_task_rating_task_id'), 'evaluation', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_task_rating_task_id'), 'evaluation', ['task_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
