"""add closed_at for Task model

Revision ID: 7f5fc42a82cf
Revises: ca5a257cd822
Create Date: 2025-08-29 10:19:24.660968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f5fc42a82cf'
down_revision: Union[str, Sequence[str], None] = 'ca5a257cd822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'closed_at')
    # ### end Alembic commands ###
