"""add TaskComent model

Revision ID: 095b229e48dc
Revises: 0badceff3860
Create Date: 2025-08-28 13:35:28.019358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '095b229e48dc'
down_revision: Union[str, Sequence[str], None] = '0badceff3860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taskcomment',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk_taskcomment_author_id_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name=op.f('fk_taskcomment_task_id_task'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taskcomment'))
    )
    op.drop_constraint(op.f('fk_task_team_id_team'), 'task', type_='foreignkey')
    op.create_foreign_key(op.f('fk_task_team_id_team'), 'task', 'team', ['team_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_task_team_id_team'), 'task', type_='foreignkey')
    op.create_foreign_key(op.f('fk_task_team_id_team'), 'task', 'team', ['team_id'], ['id'], ondelete='SET NULL')
    op.drop_table('taskcomment')
    # ### end Alembic commands ###
