"""change meeting

Revision ID: 658824f25e3d
Revises: 701c23b38582
Create Date: 2025-11-14 15:48:32.637410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '658824f25e3d'
down_revision: Union[str, Sequence[str], None] = '701c23b38582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meeting', 'starts_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_comment='Дата и время начала (с таймзоной)',
               existing_nullable=False)
    op.alter_column('meeting', 'ends_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_comment='Дата и время окончания (с таймзоной)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meeting', 'ends_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='Дата и время окончания (с таймзоной)',
               existing_nullable=False)
    op.alter_column('meeting', 'starts_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='Дата и время начала (с таймзоной)',
               existing_nullable=False)
    # ### end Alembic commands ###
