"""update nullable for assignee_id

Revision ID: 2b0785cdd51a
Revises: 3fe2832f5e28
Create Date: 2025-08-28 13:57:22.703088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b0785cdd51a'
down_revision: Union[str, Sequence[str], None] = '3fe2832f5e28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'assignee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'assignee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
