"""add ondelete politics

Revision ID: 701c23b38582
Revises: 16b1b7493e3c
Create Date: 2025-11-10 12:00:06.511991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '701c23b38582'
down_revision: Union[str, Sequence[str], None] = '16b1b7493e3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evaluation', 'task_id',
               existing_type=sa.INTEGER(),
               comment='ID задачи, к которой относится оценка',
               existing_nullable=False)
    op.alter_column('evaluation', 'value',
               existing_type=sa.SMALLINT(),
               comment='Числовая оценка выполнения (например, 1–5)',
               existing_nullable=False)
    op.alter_column('evaluation', 'rated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Время, когда была выставлена оценка (с таймзоной)',
               existing_nullable=False)
    op.alter_column('meeting', 'team_id',
               existing_type=sa.INTEGER(),
               comment='ID команды — владельца встречи',
               existing_nullable=False)
    op.alter_column('meeting', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment='Заголовок встречи',
               existing_nullable=False)
    op.alter_column('meeting', 'description',
               existing_type=sa.TEXT(),
               comment='Описание/повестка встречи (опционально)',
               existing_nullable=True)
    op.alter_column('meeting', 'starts_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата и время начала (с таймзоной)',
               existing_nullable=False)
    op.alter_column('meeting', 'ends_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата и время окончания (с таймзоной)',
               existing_nullable=False)
    op.alter_column('meeting', 'status',
               existing_type=postgresql.ENUM('scheduled', 'canceled', name='meetingstatus'),
               comment='Текущий статус встречи',
               existing_nullable=False)
    op.alter_column('task', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Название задачи',
               existing_nullable=False)
    op.alter_column('task', 'description',
               existing_type=sa.TEXT(),
               comment='Подробное описание задачи в свободной форме',
               existing_nullable=False)
    op.alter_column('task', 'deadline_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дедлайн задачи (с таймзоной)',
               existing_nullable=False)
    op.alter_column('task', 'status',
               existing_type=postgresql.ENUM('open', 'in_progress', 'done', name='status'),
               comment='Текущий статус задачи',
               existing_nullable=False)
    op.alter_column('task', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='ID пользователя — автора задачи')
    op.alter_column('task', 'assignee_id',
               existing_type=sa.INTEGER(),
               comment='ID пользователя — исполнителя задачи (может отсутствовать)',
               existing_nullable=True)
    op.alter_column('task', 'team_id',
               existing_type=sa.INTEGER(),
               comment='ID команды-владельца задачи',
               existing_nullable=False)
    op.drop_constraint(op.f('fk_task_author_id_user'), 'task', type_='foreignkey')
    op.create_foreign_key(op.f('fk_task_author_id_user'), 'task', 'user', ['author_id'], ['id'], ondelete='SET NULL')
    op.alter_column('taskcomment', 'task_id',
               existing_type=sa.INTEGER(),
               comment='ID связанной задачи',
               existing_nullable=False)
    op.alter_column('taskcomment', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='ID пользователя — автора комментария')
    op.alter_column('taskcomment', 'body',
               existing_type=sa.TEXT(),
               comment='Текст комментария',
               existing_nullable=False)
    op.drop_constraint(op.f('fk_taskcomment_author_id_user'), 'taskcomment', type_='foreignkey')
    op.create_foreign_key(op.f('fk_taskcomment_author_id_user'), 'taskcomment', 'user', ['author_id'], ['id'], ondelete='SET NULL')
    op.alter_column('team', 'name',
               existing_type=sa.VARCHAR(),
               comment='Название команды',
               existing_nullable=False)
    op.alter_column('team', 'owner_id',
               existing_type=sa.INTEGER(),
               comment='ID владельца команды (опционально)',
               existing_nullable=True)
    op.drop_constraint(op.f('fk_team_owner_id_user'), 'team', type_='foreignkey')
    op.create_foreign_key(op.f('fk_team_owner_id_user'), 'team', 'user', ['owner_id'], ['id'], ondelete='SET NULL')
    op.alter_column('user', 'role_in_team',
               existing_type=postgresql.ENUM('admin', 'manager', 'employee', name='teamrole'),
               comment='Роль пользователя в команде',
               existing_nullable=False)
    op.alter_column('user', 'team_id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор команды пользователя (FK на team.id)',
               existing_nullable=True)
    op.drop_constraint(op.f('fk_user_team_id_team'), 'user', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_team_id_team'), 'user', 'team', ['team_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_team_id_team'), 'user', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_team_id_team'), 'user', 'team', ['team_id'], ['id'])
    op.alter_column('user', 'team_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Идентификатор команды пользователя (FK на team.id)',
               existing_nullable=True)
    op.alter_column('user', 'role_in_team',
               existing_type=postgresql.ENUM('admin', 'manager', 'employee', name='teamrole'),
               comment=None,
               existing_comment='Роль пользователя в команде',
               existing_nullable=False)
    op.drop_constraint(op.f('fk_team_owner_id_user'), 'team', type_='foreignkey')
    op.create_foreign_key(op.f('fk_team_owner_id_user'), 'team', 'user', ['owner_id'], ['id'])
    op.alter_column('team', 'owner_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID владельца команды (опционально)',
               existing_nullable=True)
    op.alter_column('team', 'name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Название команды',
               existing_nullable=False)
    op.drop_constraint(op.f('fk_taskcomment_author_id_user'), 'taskcomment', type_='foreignkey')
    op.create_foreign_key(op.f('fk_taskcomment_author_id_user'), 'taskcomment', 'user', ['author_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('taskcomment', 'body',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Текст комментария',
               existing_nullable=False)
    op.alter_column('taskcomment', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='ID пользователя — автора комментария')
    op.alter_column('taskcomment', 'task_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID связанной задачи',
               existing_nullable=False)
    op.drop_constraint(op.f('fk_task_author_id_user'), 'task', type_='foreignkey')
    op.create_foreign_key(op.f('fk_task_author_id_user'), 'task', 'user', ['author_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('task', 'team_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID команды-владельца задачи',
               existing_nullable=False)
    op.alter_column('task', 'assignee_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID пользователя — исполнителя задачи (может отсутствовать)',
               existing_nullable=True)
    op.alter_column('task', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='ID пользователя — автора задачи')
    op.alter_column('task', 'status',
               existing_type=postgresql.ENUM('open', 'in_progress', 'done', name='status'),
               comment=None,
               existing_comment='Текущий статус задачи',
               existing_nullable=False)
    op.alter_column('task', 'deadline_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Дедлайн задачи (с таймзоной)',
               existing_nullable=False)
    op.alter_column('task', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Подробное описание задачи в свободной форме',
               existing_nullable=False)
    op.alter_column('task', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Название задачи',
               existing_nullable=False)
    op.alter_column('meeting', 'status',
               existing_type=postgresql.ENUM('scheduled', 'canceled', name='meetingstatus'),
               comment=None,
               existing_comment='Текущий статус встречи',
               existing_nullable=False)
    op.alter_column('meeting', 'ends_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Дата и время окончания (с таймзоной)',
               existing_nullable=False)
    op.alter_column('meeting', 'starts_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Дата и время начала (с таймзоной)',
               existing_nullable=False)
    op.alter_column('meeting', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Описание/повестка встречи (опционально)',
               existing_nullable=True)
    op.alter_column('meeting', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Заголовок встречи',
               existing_nullable=False)
    op.alter_column('meeting', 'team_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID команды — владельца встречи',
               existing_nullable=False)
    op.alter_column('evaluation', 'rated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Время, когда была выставлена оценка (с таймзоной)',
               existing_nullable=False)
    op.alter_column('evaluation', 'value',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='Числовая оценка выполнения (например, 1–5)',
               existing_nullable=False)
    op.alter_column('evaluation', 'task_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID задачи, к которой относится оценка',
               existing_nullable=False)
    # ### end Alembic commands ###
