"""Change team_fk  User mosel

Revision ID: 638d07a2ecc5
Revises: 1fecc2f1ab40
Create Date: 2025-08-23 15:16:14.162980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '638d07a2ecc5'
down_revision: Union[str, Sequence[str], None] = '1fecc2f1ab40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('team_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('fk_user_team_fk_team'), 'user', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_team_id_team'), 'user', 'team', ['team_id'], ['id'])
    op.drop_column('user', 'team_fk')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('team_fk', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_user_team_id_team'), 'user', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_team_fk_team'), 'user', 'team', ['team_fk'], ['id'])
    op.drop_column('user', 'team_id')
    # ### end Alembic commands ###
