"""add timecheck for meetings

Revision ID: a8cd8284c7d9
Revises: 1c47eecc3c91
Create Date: 2025-09-10 11:52:08.864074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8cd8284c7d9'
down_revision: Union[str, Sequence[str], None] = '1c47eecc3c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_team_status'), table_name='meeting')
    op.drop_index(op.f('ix_meeting_time_window'), table_name='meeting')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_meeting_time_window'), 'meeting', ['starts_at', 'ends_at'], unique=False)
    op.create_index(op.f('ix_meeting_team_status'), 'meeting', ['team_id', 'status'], unique=False)
    # ### end Alembic commands ###
